
#jump_to_the_end.runTest()
#k_ary_symmetrical_tree_check.runTest()
#smaller_to_the_right.runTest()
#nth_fibonacci_number.runTest()
#find_pairs_of_unique_indices.runTest()
#find_single_element_in_array_of_duplicates.runTest()
#rotate_nxn_matrix.runTest()
#compress_string.runTest()
#calc_h_index.runTest()
#largest_number.runTest()
#longest_consecutive.runTest()
#markov_chain.runTest()
#linked_list_rotate.runTest()
#level_order_traversal.runTest()
#dice_roll_probability.runTest()
#stack_interleave.runTest()
#graph_is_minimally_connected.runTest()
